### ISSUE TITLE
Pages: length of paragraphs

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#122]
@kpettinga I've noticed a few pages are using full-length paragraphs especially when the right column is empty. We'd need to make sure those paragraphs are consistent across all pages.

A few pages which are incorrect are:
http://cgu.wpengine.com/academics/?
http://cgu.wpengine.com/academics/schools/

The correct use is here on the Admissions page:

![image](https://cloud.githubusercontent.com/assets/12611145/19322528/6ee5cba8-9087-11e6-9ddf-60798851c702.png)

**Comment by kpettinga** [comment]
@elliotarthur there is an option on pages to set the content width to full or 3/4. There are cases in which the content should be full width because shortcodes are used in the wysiwyg editor which require it. From here on, if content width appears wrong, check the page content width field in the backend.

**Comment by davekellam** [comment]
Going to close this out.
