### ISSUE TITLE
Homepage: News section

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#125]
@kpettinga From Hollis: News section doesn't look like mockups. How are images added in order to appear as the featured news story on the homepage? If you add a Featured Image on the backend, it appears as the page header image on the news page (which we don't want). Also, is there a way to make the featured news post sticky?

**Comment by kpettinga** [comment]
Hey @Jessdwilson 

I've refactored the news posts layout a bit for the home page and news pages. 
- Firstly, each article is now on its own line and if there's a featured image, it appears on the left with the text on the right. If there is now featured image, the title of the article simply takes up the whole line. This was done because if you have a situation where one article has a featured images but the adjacent one does not, it becomes hard to tell which article the image belongs to.
- I've also added a tab navigation of the 3 most used tags above the post list on the home page.

If they want to make a post sticky, go into the post's edit page and click "edit" next to the Visibility label in the Publish metabox. You can then check the box "Stick this post to the front page". This makes it a sticky post and it will always show first in the list of posts.
**Note**: A sticky post will also show up on the News page.

**Comment by Jessdwilson** [comment]
@kpettinga the client has requested that Categories appear at the top instead of tags to filter the news items 

![news-categories](https://cloud.githubusercontent.com/assets/1680051/19486469/8c191a32-952c-11e6-9c58-d2a9f09070ed.JPG)
