### ISSUE TITLE
Shortcodes: issues with nested shortcodes

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#160]
@kpettinga From Hollis:

http://cgu.wpengine.com/school/drucker-school-of-management/careers/

Click on the "For Current Students & Alumni" dropdown - the column shortcodes don't work. If I move them outside the dropdown, they start working again.

**Comment by davekellam** [comment]
Shortcodes generally do work within shortcodes, but there are some limitations, which we run up against here. Nested shortcodes within nested shortcodes will not work ([codex](https://codex.wordpress.org/Shortcode_API#Nested_Shortcodes)). They're trying to use the column group inside another column group and it won't work.

So, the question is what they're trying to achieve here. It appears to be columns/lists within a dropdown shortcode. There might be an option like some sort of list short code that works within different blocks.

**Comment by kpettinga** [comment]
@davekellam @Jessdwilson they're using the first set of column shortcodes in order to create a sidebar on the page.

Since we're already providing some other sidebar options, i think we might as well give them the ability to add custom content to the sidebar as we already do with programs. This means the client won't need to use column shortcodes just to create a page sidebar. Having a sidebar content editor will also solve issue #161 **Sidebar: option with links to external sites**.

**Comment by kpettinga** [comment]
@Jessdwilson, as @davekellam stated, Wordpress has limits on how you can nest shortcodes. So I've made it easier to create sidebar content.

See http://cgu.wpengine.com/wp-admin/post.php?post=2048&action=edit for an example of how to use the new custom content option for sidebars.

There's a WYSIWYG editor for Sidebar Custom Content and then a box you can check, "Custom Content", in the Sidebar Options.
