### ISSUE TITLE
Breadcrumbs: all pages leaves off current page

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#168]
This appears to be an issue on all pages, for example on this page the breadcrumb should be Home > Academics > Schools

http://cgu.wpengine.com/academics/schools/

**Comment by kpettinga** [comment]
Hey @Jessdwilson, breadcrumbs usually denote the page structure or path that leads to your current page. Because you're already on the "Schools" page, for instance, its redundant to list it in the breadcrumbs _and_ the title of the page. Hence, the reason we leave out the current page. 

Is this something the client requested a change for?

**Comment by Jessdwilson** [comment]
@kpettinga yes, Andrea and Hollis brought this up during our call yesterday. They may be looking at how other sites have this, for example: http://www.yale.edu/admissions/graduate-professional-schools
