### ISSUE TITLE
Programs Admissions: Shortcodes

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#169]
Hollis mentioned that it would be extremely helpful if there was a shortcode for the Cost per unit info for programs so that when this info changes it will automatically update in the various locations across the site. The cost is the one item that is most likely to change over time and they need an efficient way to update the info.

**Comment by kpettinga** [comment]
@Jessdwilson can you clarify where this shortcode will be used and what it should actually output.

Couple questions:
1. I assume it will be shown on each program page and its respective cost & aid admission info post. Any other contexts?
2. Should the shortcode just output a number?
3. Where should this number/data get entered in wordpress? On each program?

**Comment by kpettinga** [comment]
**The other shortcode requested is**:

**Application Deadlines** - see current content here: http://www.cgu.edu/pages/422.asp - again, just like the tuition, there are some exceptions to this, namely the EMBA program, but almost all other programs follow these deadlines.
- - - -

Since this will need to output an HTML table of information, and not something simple like text, it might be best to just create a basic module (ie. "Admission Deadlines") with a table of info and use that to manage deadline information. Then you can pull the content from that module into any page by using the [content] shortcode. 

**example**: 
_If $moduleID = 1234_
[content post="1234" span="full"]

**Comment by kpettinga** [comment]
@holliscooper-cgu can you provide some guidance here? :

*Cost per unit info shortcode questions*:
1. I assume it will be shown on each program page and its respective cost & aid admission info post. Any other contexts where it will appear?
3. The shortcode will need to pull from a custom field in the backend. Where should this number/data get entered? On each program edit page?

*For the application deadlines shortcode*:
Please see my previous comment in this thread.

**Comment by holliscooper-cgu** [comment]
1. You are correct, cost per unit will appear in the sidebar of the program pages, and will appear in the admissions info post. I don't believe it appears anywhere else. 
2. If possible, it should go somewhere global. Ideally, there really only needs to be one place to enter it - it's a single number that will appear on all the pages mentioned above, and so the fewer places that we need to enter it, the better. There are only 2 programs (EMBA, MFA) that don't use that number, so for those cases we will manually type in the cost per unit number.

We will use your suggestion for the application deadlines module.

**Comment by kpettinga** [comment]
@holliscooper-cgu 

I've created a field for **Cost per unit** in the Program Options metabox. It's right below the Concentration field. Enter the data (e.g. "1,250") and then use the [custom_field] shortcode to grab it from anywhere else on the site.

[See the documentation for the [custom_field] shortcode >>] (http://cgu.wpengine.com/wp-admin/admin.php?page=wp-help-documents&document=6562)

**Example: Grab cost per unit data**
For the Full Time MBA program, the [custom_field] shortcode would be used like this:
`[custom_field name="program_cpu" post="full-time-mba"]`

cc: @Jessdwilson
