### ISSUE TITLE
Design Changes 10/31/2016

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#175]
Per documents from client: https://www.dropbox.com/sh/6nhi2s9gjv2fc35/AADdBiOMIaODRe6_lueNhIpGa?dl=0

We will implement color and type changes provided they don't violate any 508 compliance issues. To preserve site performance we've recommended using only 1 weight and style for Mercury 

With regards to the header/navigation changes, we can implement changes to the type treatment but everything else will need to be part of Phase 2 

---

**Note**: items with 🚩   have caveats associated with them. See first comment below.

**Global Changes**
- Color Updates 🚩 
- [x] Update typography
- [x] Update "more" links
- [x] Update footer color
- [x] Update sidebar style
- [x] Use Dark gray for default header

**Home**
- [x] Section headline size changes
- [x] Events Section color changes 🚩 
- [x] Use Gotham Bold for year numbers

**Academics**
- [x] Program filter bar colors
- [x] filterbar down arrow on selected filters 🚩
- [x] Program result color updates
- [x] Order areas into columns

**Research**
- ~~Sponsored Research section background~~ 🚩
- [x] Featured Research section color/type changes 🚩

**10 Reasons**
- [x] Type and color changes

**Single Program**
- sidebar button styles 🚩
- [x] featured courses type change
- [x] tighten up areas of concentration
- [x] curriculum breakdown color changes
- [x] faculty profile: names smaller

**Comment by kpettinga** [comment]
**Global Changes**
*Accessibility issues*:
- We cannot darken the red to #9b1210 because it causes color ratio issues with dark gray and black. Color ratios need to be 3.0 or higher. See the [WebAIM Contrast Checker](http://webaim.org/resources/contrastchecker/) to check color ratios.

**Comment by kpettinga** [comment]
@holliscooper-cgu, @Jessdwilson:

I've contacted Greg to get us setup with a separate clone of the site where we can preview design changes. 

As you can see from my comment above, we addressed color changes where possible, provided they would not interfere with accessibility standards. In some areas I've taken the liberty of falling back to an acceptable color like using black instead of teal for the headline of a tan colored module. 

On the new site I've asked Greg to setup, you'll be able to see the changes that we've made. Stay tuned.

cc: @jalbertgagnier

**Comment by Jessdwilson** [comment]
@kpettinga following feedback from faculty, Andrea and Hollis brought up a couple additional design changes that need to be made: 

On the homepage, remove the Areas of Study sidebar. We will need to replace this with a module on the homepage along the lines of the attached screenshot from UC San Diego with a link to Schools and a link to Programs

On the Academics page the Filter By sections for Areas of Study and Degrees should remain open by default 

![screen shot 2016-11-18 at 9 42 48 am](https://cloud.githubusercontent.com/assets/1680051/20503444/86415a62-b010-11e6-8012-e670b934d385.png)

**Comment by kpettinga** [comment]
@Jessdwilson spinning this off into its own issue: #271

**Comment by kpettinga** [comment]
@holliscooper-cgu @Jessdwilson 

http://cgudesign.wpengine.com/ is now tracking a new branch with the design changes from the October 31st document. The changes included typography tweaks for headlines and color changes for sections, written content, and UI elements.

As stated above, there were many cases where accessibility rules interfered with color changes so I did my best to address those with fallbacks to color that _would_ work in their contexts.

cc: @jalbertgagnier

**Comment by Jessdwilson** [comment]
Thanks! @kpettinga 

- [ ] Under Faculty can the "View Profile" links be tan as they are in the design mockup?
- [ ] On the Academics Programs when the filters are open it's the dark teal can this be updated to the teal shown in the design mockup or does this violate compliance issues? 
![cgu design mockup - faculty](https://cloud.githubusercontent.com/assets/1680051/20544508/70c35226-b0d8-11e6-9d6d-594e344a934e.png)
![screen shot 2016-11-22 at 5 16 48 pm](https://cloud.githubusercontent.com/assets/1680051/20544523/77cc66d4-b0d8-11e6-8955-e58d97d1f136.png)

**Comment by kpettinga** [comment]
@Jessdwilson 

Per the accessibility guidelines for color contrast, the "more" links cannot be tan at their current size. They're too small.

For the filter menus, these can be updated to teal because the text is large enough. Tan, however, cannot be used as text color on teal. I will updated the site accordingly.

**Comment by Jessdwilson** [comment]
thanks! @kpettinga the "Areas of Study" on the programs filter is stacked instead of single line when I view it in Chrome and Safari, can you fix? 

![screen shot 2016-11-23 at 10 07 10 am](https://cloud.githubusercontent.com/assets/1680051/20566871/a2643728-b164-11e6-8f83-a67f75e21a61.png)

**Comment by kpettinga** [comment]
@Jessdwilson all set.

**Comment by holliscooper-cgu** [comment]
Additional comments from Andrea:
•	The “More>” style wasn’t implemented, can we?
•	On the homepage of cgudesign.wpengine.com can you please make “History of CGU” tan instead of black–whenever title text is on white it should be tan
•	On the timeline the font size is too big, also the placement of text here is correct or is it correct on cgu.wpengine.com? 
•	On the program pages, the teal bar at the top of the sidebar is a little too thick
•	Areas of concentration need to be black then red on rollover
•	On the Academics landing page, can you make all the areas of study/degree headers Mercury? See screenshot:
![headers](https://cloud.githubusercontent.com/assets/18012084/20851841/942aedd4-b897-11e6-9ae8-721d20d68181.JPG)

**Comment by holliscooper-cgu** [comment]
Also, we found this design error (black link text that should be white) on cgudesign.wpengine.com - it's not on the main site, and we just want to make sure it doesn't accidentally get carried over:

![image](https://cloud.githubusercontent.com/assets/18012084/20852174/505a8b6c-b899-11e6-86b0-a335fd3983b1.png)

**Comment by kpettinga** [comment]
@holliscooper-cgu this issue is getting pretty dense. Let's break this up into a series of issues so they're easier to keep track of.

**Comment by kpettinga** [comment]
@holliscooper-cgu I'm going to break this up into a series of issues as this one is getting pretty dense and hard to keep track of.

**Comment by holliscooper-cgu** [comment]
@kpettinga Ignore the More> style for now - what's being done currently is fine. The Areas of Concentration are on the program pages, but this relates to the larger issue of links being black with red rollover, and not vice-versa.

**Comment by kpettinga** [comment]
Closing this issue and spinning out into separate issues for the sidebar #306 and header nav #307
