### ISSUE TITLE
Header overlay text: black text option

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#185]
The client will be adding photos to page headers, in our mockups we showed options with black text as well as white text. Could there be an option on the WP pages to select the text color? 

![screen shot 2016-11-04 at 6 42 17 pm](https://cloud.githubusercontent.com/assets/1680051/20024716/99ec2092-a2be-11e6-91e4-64af9775c891.png)

**Comment by kpettinga** [comment]
@Jessdwilson you can now select whether text should be black or white and whether it should be on the left or right side of the header. 

Because you can now dictate the text color, I've removed the scrim when there's a hero image. Text color should be selected accordingly.

For headers with carousels, like some schools, header text will always be white and on the left for each slide. The scrim remains for carousels as well.
