### ISSUE TITLE
SAH Art Department page: order of information

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#198]
We have added galleries which automatically appear on the Art Department page, but the order of items doesn't match our mockups: https://www.dropbox.com/s/7xoeode73xg1ejf/CGU%20SAH%20Website%20Design%20Refinements%2020160727.pdf?dl=0

http://cgu.wpengine.com/departments/art/

The facilities module should appear before the galleries. 
Under Art Galleries, the MFA Students should appear before Faculty.
Visiting Artist Lecture Series should appear before the History of the Art Department timeline

**Comment by kpettinga** [comment]
@Jessdwilson you can now use the Order field on gallery terms to organize the galleries. I've set it up on the live site already.

I've added an Upper Modules field so that you can add modules, like Facilities, before the art gallery carousel.

The Visiting Artist Lecture Series and Art Department timeline are both modules. You just need to rearrange them in the order you like.
