### ISSUE TITLE
Page with Sidebar template: Add upper module location

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#206]
We need an upper module location for non-program pages. We use the page with sidebar option the most. The layout should be: text area | upper module | lower content area | lower module

For pages with a mix of module/text content, this will better visually break up the page. 
Ex. http://cgu.wpengine.com/academics/resources-support/

**Comment by kpettinga** [comment]
@holliscooper-cgu 

The reason we needed to add the upper modules field to programs was because there is content baked into the template that you weren't originally able to put modules on top of. 

On pages however, there is no other content besides the default text area that is programmed to show up on the template. So if you want a text block in between two modules, you just need to create a "Basic" module with your text and add it to the page.

**Comment by holliscooper-cgu** [comment]
Ok, will do.
