### ISSUE TITLE
Admission Info: Cost Per Unit shortcode

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#213]
Since the majority of programs have the same cost per unit Hollis has created a general post under Programs for the cost per unit: http://cgu.wpengine.com/wp-admin/post.php?post=6584&action=edit

She would like there to be a single place to update this information so that all programs associated with it will update if it changes and thought we could use the content shortcode in the Program Options section to pull this post. 

@kpettinga you suggested we might want to create a global field for this in the customizer to avoid the content shortcode becoming unwieldy

**Comment by kpettinga** [comment]
@holliscooper-cgu 

Instead of creating a program just for housing universal cost-per-unit data, I've implemented a field in the theme options to hold this data and made a new [program_cpu] shortcode.

To enter a universal cost-per-unit number, log in and go to **Appearance** > **Customize**. On the page that follows you'll see a tab on the left called **Global Data**. Click that and you'll see a field where you can specify a global **Cost Per Unit** number.

Once you've entered that, use the [program_cpu] shortcode to display the number. It will automatically look to see if the program has it's own value and if it doesn't, it will get the global value.

cc: @Jessdwilson

**Comment by kpettinga** [comment]
If, for some reason you still want to get data from a specific program and you're not using the shortcode on that program, you can specify a "post" value like so:

**with program slug**: `[program_cpu post="positive-health-psychology"]`
OR
**with program ID**: `[program_cpu post="1907"]`

[Click here to read the documentation](http://cgu.wpengine.com/wp-admin/admin.php?page=wp-help-documents&document=7021)
