### ISSUE TITLE
Application Checklist: floating content

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#215]
We are updating the admissions info and have found that there is a float in the CSS where the content appears side-by-side, this is happening on the Application Guidelines pages of programs and on the Admissions How to Apply pages 

Unique Application Requirements should appear below Application Checklist 

![program application guidelines](https://cloud.githubusercontent.com/assets/1680051/20151757/5bb78f7c-a689-11e6-9e66-c5a1c5b41289.png)
![admissions how to apply](https://cloud.githubusercontent.com/assets/1680051/20151767/63b4396e-a689-11e6-90c0-cc64ddcae4ff.png)

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu 

This was happening because the [content] shortcode came with a "span" attribute built into it. This would let you dictate how wide the content should be. But I realized it's best to try and silo shortcode responsibilities as much as possible. 

So I've removed the "span" option on the [content] shortcode.
