### ISSUE TITLE
Module option: separate text and photo

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#226]
Could we have a module option with a vertical image and text separated and have the option to choose black or white text? There are some modules where the client expects to have a larger amount of text and when displaying the text over an image it can muddle the photo, for example see the Claremont Colleges Library modules at the end of the Resources & Support page: http://cgu.wpengine.com/academics/resources-support/

**Comment by kpettinga** [comment]
@Jessdwilson you don't need options for this because I'm pretty sure it can already work. I need some clarification on what you're trying to do though. What do you mean by "vertical image"? 

If you don't want the image to be the background of the module, just switch it to a Basic module type, remove the featured image and add the image inside the text editor itself ("add media" button). 

Either assign an alignment to the image or use the column shortcodes if you want the image and text side-by-side.
