### ISSUE TITLE
Academics: Program filters

### ISSUE THREAD

**Issue by elliotarthur** [ObjectiveSubject/cgu#235]
@kpettinga I have a couple of design and UX changes here, I'll create a list to help make these digestible. 

- [ ] The selected program bar doesn't stick to the main navigation when scrolling down. This might be useful especially when the user selects multiple programs.
- [ ] Make the text in the box h4 and black text.
![image](https://cloud.githubusercontent.com/assets/12611145/20218279/c6ffdce4-a7f1-11e6-831d-c5e5d48103f9.png)

- [ ] Change the program text to h4 & Black also to match the "Masters and Doctoral" boxes.
![image](https://cloud.githubusercontent.com/assets/12611145/20218311/f16ae6b8-a7f1-11e6-93d4-512371ebd0b6.png)

- [ ] Even though we're in the Academics section shouldn't the page header say programs? I went to change the header but the entire nav etc changed. I think I want to clarify this is the programs page without having the sub-header saying Programs below the lead paragraph. I thought it would be Academics is the section and programs is the page. (cc. @Jessdwilson) 

- [ ] We should change those subheaders which talk about filtering. If we need two messages to prompt the user then the first message isn't clear enough. Should the first message say: "FILTER THE OPTIONS TO NARROW YOUR SEARCH"?! (cc. @Jessdwilson) 

- [ ] @Jessdwilson can we recommend an image in the header as this is one of the most important pages on the site?!

**Comment by Jessdwilson** [comment]
@elliotarthur I don't have any strong feelings about adding Programs to the header, so if you think this should be adjusted to make it more clear we can make that change.

The client is working away at getting photos added to headers

**Comment by elliotarthur** [comment]
I think we should change it so we're not cluttering the page with unnecessary sub headers.

**Comment by kpettinga** [comment]
@elliotarthur, @Jessdwilson  a lot of what's talked about here may be irrelevant with the new design changes that we've done (cgudesign.wpengine.com). 

RE:
> The selected program bar doesn't stick to the main navigation when scrolling down. This might be useful especially when the user selects multiple programs.

I'm confused. What is the "selected program bar" and what do you mean by "selecting multiple programs"? That isn't something you can do.

- In terms of the degree type and area of study headers, the client has specified a new look for these in the design changes.
- Changing the page name in the header to Programs does make a lot of sense. But the problem is that they still want to maintain the "Academics" link in the header. So I think it's confusing to click on Academics and then be brought to a page called "Programs".
- The subheaders which talk about filtering have been updated in the new design changes.

**Comment by holliscooper-cgu** [comment]
Just wanted to follow up from our end. 
- Kirk is correct that the design changes are taken care of in the new look & feel. 
- Academics should stay Academics in the nav and we are okay with using "Programs" as a custom title on that page.
- We're okay with the heading bars not sticking when you scroll down the program page.
