### ISSUE TITLE
Get array of post date archives

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#24]
On the `index.php` and `date.php` templates, I want to be able to set the `selected` attribute on the correct option in the Date select field.

I have a select field for School, Date, and Tag. I'm referring to the `$_SERVER` variable to get the existing values for any of these so when the page loads, the correct options are selected. This is easy enough with School and Tag because I can iterate through an array and whichever option value matches gets the `selected` attribute.

With the Date select field, however, all I seem to be able to do is use `wp_get_archives()` to generate a list of options, but it returns them to you as html, not an array. So I can't use the same matching technique to add the `selected` attribute to the proper option.

Know another way to get an **array** of post archive links that i can loop through manually? I don't want to have to use Javascript to set the selected options b/c im already using PHP with School and Tag.

![image](https://cloud.githubusercontent.com/assets/1746410/15493126/08496246-21ac-11e6-8975-eee056ec2cce.png)

**Comment by davekellam** [comment]
We should probably use `home.php` (it's the "blog" home page) rather than `index.php`, and keep index.php as a catch-all fallback, just in case something sneaks through.

I don't we should be using `$_SERVER['QUERY_STRING']`, especially with no sanitization or checks. We should be able to achieve the same results with `get_query_vars()`, although they may need to be setup initial with `add_query_vars` if they're not ones that are already there.

I'm not entirely sure how cacheable these things are. May need to keep on eye on that. 

I'll see what I can do about a solution to the date issue. Assuming it's by month/year? That could be tricky.

**Comment by kpettinga** [comment]
We're just using regular archives now so this has become significantly less complicated.
