### ISSUE TITLE
Video modules: black bars appearing

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#246]
In some YouTube videos, the display incorporates black bars above and below the video. See: http://cgu.wpengine.com/school/school-of-arts-and-humanities/

**Comment by kpettinga** [comment]
@holliscooper-cgu those are the screenshots that YouTube is generating. We're just pulling from what their API gives us. You can define a custom screenshot for a video in a video's settings. You'll want to make sure that it's in a 16x9 aspect ratio and at least 1280px wide (so 1280x720px).

**Comment by kpettinga** [comment]
@holliscooper-cgu I've updated the code so that the preview images for videos will be css background images as opposed to <img> elements. Because the video containers are 16x9 and a lot of the black bar images are 4x3, this should help hide the black bars. 

However there are some videos who's preview images have black bars even though they're 16x9. For those, you'll want to do what I suggested above; manually set a 16x9 screenshot in the video's settings on YouTube.
