### ISSUE TITLE
Subnavigation display issues in Safari

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#251]
We're seeing strange sub-nav display issues in Safari for some pages. 

Ex. http://cgu.wpengine.com/about/
See attached screenshot. 
![screen shot 2016-11-13 at 4 15 16 pm](https://cloud.githubusercontent.com/assets/18012084/20250077/50755e96-a9bd-11e6-89d3-ab6ff37c1e70.png)

**Comment by kpettinga** [comment]
@holliscooper-cgu this is happening because the menu items are too long for the space they're allotted. We've implemented CSS for this situation so that the list items will break their text into 2 lines rather than move an entire list item to a new row. 

If we remove that CSS and let the list items flow to 2 rows it will look like this:
![image](https://cloud.githubusercontent.com/assets/1746410/20254128/e7e583ea-aa63-11e6-80d6-d453d1568f3b.png)

Either way, the menu items are too long. You can try to shorten them or choose to hide the "About" link in the Sub-Navigation options box for this page. That may help to free up some space:
![image](https://cloud.githubusercontent.com/assets/1746410/20254143/1289898e-aa64-11e6-8b3c-80b6095ee524.png)

**Comment by holliscooper-cgu** [comment]
@kpettinga - this only happens in Safari, though, that we've seen. That page looks fine in Chrome.

**Comment by kpettinga** [comment]
@holliscooper-cgu 

When content gets tight, browsers will handle content breakpoints slightly differently. This isn't a CSS bug, the menu items just need to be shorter.

> [...] You can try to shorten them or choose to hide the "About" link in the Sub-Navigation options box for this page. That may help to free up some space.
