### ISSUE TITLE
Access Levels/Roles

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#285]
We are waiting to hear back from the client with more information about who should have access. 
The bullet points below are from CGU's reqs doc and appear to list nearly everyone, but it's our understanding that a smaller subset of people should be given access

@davekellam are you familiar with the WordPress Members plugin CGU suggests below? 

Restrict users to specific areas of the site, from broad areas down to individual programs and offices, and customize control levels of editing access within those areas. 

- WP plugin: Members (or similar)
   https://wordpress.org/plugins/members/

- Examples of access organization/roles/levels:

Schools/Institutes/Centers (Ex. Drucker School; School of Education; School of Social Science, Policy, & Evaluation; Institute of Mathematical Studies, Center for Information Systems and Technology, School of Community and Global Health).

Academic Departments (Ex. Behavioral and Organizational Sciences; Politics and Economics, Teacher Education).

Individual academic programs (Ex. Art, Music, MBA, Psychology).

Administrative divisions (Ex. Academic Affairs, Advancement, Student Services, Finance, etc.).

Administrative offices (Ex. OIT, Financial Aid, HR, Marketing, President’s Office, Registrar, Transdisciplinary Studies, Writing Center, etc.).

Labs / Journals / Student Group pages (Ex. Foothill Journal, STEAM journal, Kay Center for e-health research, Graduate Student Council).

Individual pages / apps (Ex. News and calendar feeds on school or program pages, blogs). If CGU can get hyper-granular, perhaps even restricting users to certain tags or categories in news or calendar postings.

**Comment by Jessdwilson** [comment]
@davekellam CGU replied:

On the whole, we will at least need to restrict access by post types, pages, etc. - basically the left-hand content item options on the WP Admin menu (Posts /Events/News/People/Pages/Admissions Info/ ... and so on)
 
Here are some likely example cases:
- Person A needs access only to the Events Calendar.
- Person B needs access only to certain pages within the Pages section (this would be more restricted access than just access to the Pages type overall)
- Person C needs access to add and edit News (Posts) items
- Person D needs access to just the Spark
 
There could be crossover here, too - meaning, Person A might need access to the Events Calendar and the News posts.
 
I'm not sure how this affects access to the Media folder, since, for all of these options, those users would need to be able to upload images to the site.
 
We will _not_ need to permission out admin-level things like Appearance, Menus, Plugins, Users, Tools, Settings, etc.

**Comment by davekellam** [comment]
Ok. So both the Members plugin and the Section Editor plugins have been activated. 

**Person A**
I've used Members to setup a role called Events Editor (`event_editor`), which should limit a user to the Events vertical. It did require a few tweaks to the code, mostly around making sure the Events Type taxonomy and Hobsons import tool could be used (both things added in). You can see the current Roles and add new ones by visiting the pages under the Users vertical (Users > Roles).

**Person B**
The Section Editor plugin creates a specific role called Section Editor (it should not be altered using the Members plugin). This plugin allows for the creation of Section Groups, which limited users to specific posts in hierarchical verticals like Pages. To create new groups, you select the Section Groups area from the admin sidebar. You then apply the section editor role to the desired user and they'll be limited to that group. You can apply multiple roles to users. 

I haven't created any groups because I'm not sure how they want to limit people.

**Person C&D**
Both of these should be doable. I can look into them and see if any code needs to be added (likely some tweaks for both). Are these both desired?

**Comment by Jessdwilson** [comment]
thanks @davekellam regarding C&D I'm not sure what you mean, they need both role options

**Comment by davekellam** [comment]
I've created Roles for both News Editor and Spark Editor. They should be limited to their respective areas of the site. I tested it out locally with new users that had only the role applied. I've replicated the same settings on the CGU site. They may want to create some new users to test this out (was a bit hestitant to add more to the main site).

**Comment by davekellam** [comment]
Going to close this out, as it's quite broad. If there are over-arching questions feel free to reopen, if there are specific new roles needed or questions about specific setup elements, new issues might be better.
