### ISSUE TITLE
Custom Curriculum tables

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#286]
We want to use the curriculum module formatting on pages other than program pages. Can this be made into a module type?

One change from the existing program page module display is that we'd like the table column/row headings to be fully customizable/override-able, not just the Year 1, Year 2, etc. labels. (so, for example, 'units' could be turned into 'hours', or the semester breakdowns could be labeled as something else).

**Comment by kpettinga** [comment]
@davekellam could you setup a series of fields for this? It's pretty much identical to the curriculum fields we already setup for programs but they want some more flexibility with some of the labels (see note above).

**Comment by davekellam** [comment]
@holliscooper-cgu to clarify here, you would like to achieve this sort of table layout, but have every label (other than the Curriculum Breakdown title) customizable?

<img width="1070" alt="screen shot 2017-01-10 at 2 07 31 pm" src="https://cloud.githubusercontent.com/assets/60804/21820574/3c09cfe2-d73e-11e6-97fc-b3e583a2aa8a.png">

I'm asking because the implementation of the curriculum table on programs was highly specific/oriented towards that specific data set. With everything customizable, it becomes a lot closer to a generic set of tables and might warrant a different approach (i.e. some sort of of generic table interface rather than a whole bunch of "overrides" cluttering up the interface).

**Comment by davekellam** [comment]
I'm starting to think we may be better served by some combination of shortcodes and table layout within the main editor. It would likely offer a lot more flexibility. This sort of solution could also be used in the _basic_ module type.

One of the reasons that the curriculum breakdown was created as custom fields, was to achieve the specific positioning in the page layout at the time.

**Comment by holliscooper-cgu** [comment]
@davekellam That sounds okay to me - some kind of table layout that mimics the curriculum layout would be a totally acceptable solution. If we wanted to use it on a program page, the middle module location would work for inserting it (as a basic module).

**Comment by davekellam** [comment]
Hmm, attempted implementation of this and it's a bit of a rabbit hole. Mostly in terms of applying `table--striped` to the table itself, plus the classes for the caption and table header titles. Might need to go back to the custom field approach. 

The problem with making everything super-customizable is that you tend to need repeater fields within repeater fields, which can lead to random data loss in some server configurations ([as we've experienced](https://github.com/WebDevStudios/CMB2/issues/348)), we might be fine on WP Engine though. That or having tons of overrides, which leads to a bit of a gnarly interface.

**Comment by kpettinga** [comment]
@holliscooper-cgu we have a [table] shortcode setup now so that you can create your own curriculum tables. This needs to be used in tandem with the table button in the wysiwyg editor. the table button lets you create and manage custom tables. The [table] shortcode **should wrap** the actual table that you create.

**Table Button**
![image](https://cloud.githubusercontent.com/assets/1746410/21882932/3f30fd60-d8df-11e6-924e-e4fe02decd30.png)

Here is an example of how you would set this up. First, write the table shortcodes out with a space between them:
![image](https://cloud.githubusercontent.com/assets/1746410/21883137/3edadbe6-d8e0-11e6-97f2-2b0e4f56d94b.png)
Then, with your cursor between the opening and closing shortcode tags, use the table button to insert a table of your desired size.
![image](https://cloud.githubusercontent.com/assets/1746410/21883172/6c7900fa-d8e0-11e6-9074-b38793bf2388.png)
The table will be created but without any data in it, it looks very small. Just begin typing to enter content. Use tab or shift+tab or your mouse to move between cells.
![image](https://cloud.githubusercontent.com/assets/1746410/21883044/bc9ca466-d8df-11e6-92bb-66cd95f6a187.png)
As you can see, the table shortcode WRAPS the actual table. 

The last thing that is important to do is to make sure the top row and cells of your table are set as a heading row/cells. This is what will give them their styling. Just put your cursor in the top left cell and click the table button. Go down to **Row** and a sub-menu will appear. Click **Table Row Properties**. In box that appears, select "Header" for the **Row Type**.

Next, for each cell you'll need to set it as a "header cell". Place your cursor in each cell of the top row and click the table button. Go down to **Cell** and then select **Table Cell Properties**. In the box that appears, select "Header Cell" for the **Cell Type**.

All done! This should output the following:
![image](https://cloud.githubusercontent.com/assets/1746410/21882925/37e04458-d8df-11e6-88b7-e9c51c132e48.png)

**Comment by holliscooper-cgu** [comment]
We looked at the design of this module (both as the curriculum module, and as the table module). We like the white/gray alternating rows - the only tweak we want to make is the background color (and text color on top of it). The background of this module should be **50% opacity of the current teal color**. For ADA color-contrast, the text on top of it should change from white to black. See attached screenshot.

![newcurriculumbackgroundcolor](https://cloud.githubusercontent.com/assets/18012084/21907733/a564dc06-d8c5-11e6-90bb-176ba1307c8a.jpg)
