### ISSUE TITLE
Sidebar Nav

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/cgu#306]

**Comment by holliscooper-cgu** [comment]
One thing I've noticed with the new sidebar nav is that all program pages now automatically have the request info/visit/apply buttons. We need to be able to choose if these appear or not - for some programs (ex. Drucker's Salesforce and Leadership Arc programs) these won't be relevant, and might even be confusing since there won't be a request info option for that program in the Hobsons form, and there could also be an alternate application process.

**Comment by Jessdwilson** [comment]
@kpettinga The new sidebars still have the teal bar over the navigation but Andrea would like us to replace these with the new designs that Elliot mocked up with the grey box 

@holliscooper-cgu can you confirm that this is correct? 

![screen shot 2016-12-15 at 5 34 07 pm](https://cloud.githubusercontent.com/assets/1680051/21244690/c93cf08a-c2ec-11e6-879c-975d47bb9f25.png)

**Comment by kpettinga** [comment]
@holliscooper-cgu I will go ahead and provide the option for you to select which buttons appear.

@Jessdwilson, you're right, I misread hollis's comment about it. I've updated the design to reflect the latest design mockup.

**Comment by Jessdwilson** [comment]
@kpettinga we have the option to edit/delete the CTA buttons from the program overview box but we need the option to include/hide the CTA buttons from the sidebar navigation on program pages like we've done for other pages 

![screen shot 2016-12-16 at 1 19 12 pm](https://cloud.githubusercontent.com/assets/1680051/21273597/5604102a-c392-11e6-8044-998e019675d7.png)

**Comment by kpettinga** [comment]
@Jessdwilson @holliscooper-cgu this is all set. There are now options to *_hide_* cta buttons on programs. This is the opposite of the way pages work, where you check the buttons you want to **_show_**. 

![image](https://cloud.githubusercontent.com/assets/1746410/21300278/240634e6-c5d5-11e6-9a7f-463e3802cfd1.png)


They're flipped because the majority of programs will have these buttons and if we set it up the same way as pages, where you select which buttons to **_show_**, we'd have to go through and update every program.
