### ISSUE TITLE
Academics: Degree filter problems

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#333]
The 'interdisciplinary concentration' and 'certificate and non-degree' filters are not loading - I just get the spinning red circle. I cleared my cache and tried in both Chrome and Firefox - same result.

**Comment by kpettinga** [comment]
@holliscooper-cgu thank you for catching this bug. An error is occurring because some of the programs do not have Areas of Study assigned to them (Salesforce, for instance). In order for the results to be properly sorted, they need to have at least one Area of Study (because the programs are divided into area of study groups). If none are appropriate to some programs you should create a generic or catch-all area of study.

I've implemented a catch so that users won't get an error, but programs without an area of study will be omitted.
