### ISSUE TITLE
Program pages: Curriculum alignment

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#334]
Can this module align the columns from year to year? (e.g. Courses in Year 1 should align with Courses in Year 2, etc.) See screenshot.

![curriculum-alignment](https://cloud.githubusercontent.com/assets/18012084/21864926/b6d10de8-d7f8-11e6-8992-93e6ef0ee5f0.JPG)

**Comment by kpettinga** [comment]
@holliscooper-cgu I've set percentage width for table cells so that they should align now.

I also want to bring up the difference in contrast between the odd rows and the even ones. Odd rows get a white background with black text while even rows get a teal background with black text. The difference in contrast between the two is quite sharp and therefore it seems to disrupt the hierarchy of the information. The even rows feel much more similar to the headings (semester, courses, units). 

I would strongly suggest we try to differentiate each row with some more subtly. Perhaps a very light gray?
![screen shot 2017-01-12 at 12 11 53 pm](https://cloud.githubusercontent.com/assets/1746410/21877966/801fadf8-d8c1-11e6-98ff-b94baea83cae.png)
![screen shot 2017-01-12 at 12 12 55 pm](https://cloud.githubusercontent.com/assets/1746410/21877967/80225c56-d8c1-11e6-8ed9-3db20eb0fffd.png)

**Comment by holliscooper-cgu** [comment]
@kpettinga We are in agreement about the color issues - let me talk to Andrea and confirm (or tweak) the fixes that you've implemented. Thanks!

**Comment by holliscooper-cgu** [comment]
@kpettinga See my comment on this issue for design tweaks: #286
