### ISSUE TITLE
Submit an Event page

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#342]
@kpettinga The breadcrumbs on this page are blue instead of white and are grey on hover: http://cgu.wpengine.com/events/community/add

Also, is it possible to adjust the size of the containers so there's more space around the text? 
![breadcrumb](https://cloud.githubusercontent.com/assets/1680051/22029565/f2ac0af2-dca8-11e6-9061-f3023e7f3c37.png)
![submit an event](https://cloud.githubusercontent.com/assets/1680051/22029570/f44c76a8-dca8-11e6-9763-08f894681b9b.png)

**Comment by kpettinga** [comment]
@Jessdwilson this is happening because of the new updates to the community events plugin. Seems they've added a lot of new styles which are conflicting with ours.

@davekellam could you help me figure out a way to dequeue the `tribe_events-community-styles-css` stylesheet? That's the ID of the `<link>` tag in the head so I'm assuming its the registered name of the stylesheet in the plugin as well. 

Once that stylesheet is removed I can make a few more adjustments to our own styles and it should be fine.

**Comment by davekellam** [comment]
I tracked this down eventually, was sort of annoying to figure out! Ended up just being `tribe_events-community-styles`. That stylesheet had `select2` and `datepicker` as dependencies as well. So, I added in the relevant lines to queue them back up again if needed, you'll just need to uncomment them.

**Comment by Jessdwilson** [comment]
thanks @davekellam any idea why a calendar is now appearing below the footer?

![screen shot 2017-01-24 at 5 00 08 pm](https://cloud.githubusercontent.com/assets/1680051/22268755/aa9f2cb8-e256-11e6-8ba9-70756eb76336.png)

**Comment by davekellam** [comment]
Ooops, never scrolled all the way to the bottom. That was the datepicker script I had mentioned, I've added that back in.

**Comment by kpettinga** [comment]
Plugin is updated and i simplified the styles a bit so that the Events Calendar JavaScript can function properly.
