### ISSUE TITLE
Juicer feed embed: style issues

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#346]
We are including a Juicer feed on the site: 
http://cgu.wpengine.com/news-events/social-media/

For some reason, the feed is showing bullets for its li elements. It should look more like it does when viewed on Juicer: https://www.juicer.io/feeds/cgu

There is a Juicer WP plugin, which I haven't implemented - right now the feed is just being pulled in with Javascript. Do you guys have any thoughts on how to remove the bullets here without disturbing the rest of the theme?

**Comment by kpettinga** [comment]
In order to get the bullets right we had to implement styles for list items in text boxes that would put a 5px tan square before each item. The Juicer feed is built with a unordered list <ul> element but it's styles don't know to hide what we've done.

I put a small fix in our stylesheet to hide them on the juicer feed
