### ISSUE TITLE
Breadcrumb issues

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#349]
### Events Calendar

When you click on Events (http://cgu.wpengine.com/events/), the breadcrumb nav says "Home › Student Life › Campus Life › Spark Blog › Events Calendar"

It should just say "Home > Events"

I would also make the page heading on this page say "Events Calendar" instead of just "Calendar," because we have another calendars page on the site (where the academic calendars live). In addition, this same heading should appear on the pages that say "Events Calendar Archive"
ex. http://cgu.wpengine.com/events/category/alumni/?tribe_events_cat=alumni&tribe-bar-date=2017-02&tribe_eventcategory%5B%5D=112

### Art Galleries

For some reason, the breadcrumb for the Spark is showing up in random places. See: 

http://cgu.wpengine.com/gallery/mfa-2016-students/
http://cgu.wpengine.com/gallery/mfa-2017-students/
http://cgu.wpengine.com/gallery/recent-mfa-graduates/
http://cgu.wpengine.com/gallery/faculty/

![art-gallery-breadcrumb](https://cloud.githubusercontent.com/assets/18012084/22228156/20073d2a-e184-11e6-9f55-de2f8e4c128f.JPG)

### News 

The Spark Blog is showing up on category, school, and tag pages.

![news-breadcrumb2](https://cloud.githubusercontent.com/assets/18012084/22259012/932a05fa-e218-11e6-902a-7ea21d3ca254.JPG)

**Comment by holliscooper-cgu** [comment]
Updated to add News pages

**Comment by davekellam** [comment]
Think this is sorted now.

@kpettinga there was a small logic flaw, `is_archive('spark_cat')` rather than `is_post_type_archive('spark_cat')`. `is_archive()` doesn't accept parameters, so anytime is was hitting any sort of "archive", so the result was true. Although, reading this now, I'm guessing we actually want `is_tax('spark_cat')` because I think that's a taxonomy rather than post type.
