### ISSUE TITLE
Events: Main calendar view design modifications

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/cgu#364]
Details to come/

**Comment by Jessdwilson** [comment]
@kpettinga the client has requested that we make some CSS changes to the events calendar, 
they like the way [Pomona College](https://www.pomona.edu/events/week/2017-W06) is handling their events so that by week/month, it aggregates all the events on a single date with a clear day and date heading. They sent the attached mockup of the changes they would like to implement. Let me know if you have any questions! 

[CGU-WebsiteRefinementsEventsPageColorBoxes v3[2].pdf](https://github.com/ObjectiveSubject/cgu/files/764791/CGU-WebsiteRefinementsEventsPageColorBoxes.v3.2.pdf)

**Comment by holliscooper-cgu** [comment]
One more addition to this - any place that the event cards are shown, can we add a space between the time and the AM or PM?

![image](https://cloud.githubusercontent.com/assets/18012084/22941784/c016a9c2-f29b-11e6-9c6c-50b7e2f7cbc6.png)

**Comment by davekellam** [comment]
I've implemented the design changes for the most part. I feel like the link color should stay red, rather than change to black. It's the default link color that we've been using for the `tan-30` background color. It also helps to indicate that there's actually a link there.

**Comment by Jessdwilson** [comment]
Thanks! @davekellam I do see that we are using red text on tan backgrounds, but in some cases we are also using black text on tan backgrounds with a red hover state, for example [school footers](https://www.cgu.edu/academics/program/ma-english/). For the Events page, we would recommend black text with a red hover state, we think users will understand this is a link when they hover over it. 

Also, in mobile the "View Events By" section should appear above the listing of events, similar to how the News page is setup. 
![img_5233](https://cloud.githubusercontent.com/assets/1680051/23170375/f45e691e-f81c-11e6-8012-f18a18b5361e.PNG)
