### ISSUE TITLE
Why CGU: Update reason 1 bubbles

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/cgu#368]
![bubbleinfographic v4](https://cloud.githubusercontent.com/assets/60804/22517912/b9e8b5e0-e878-11e6-8895-857917c4a992.png)

**Comment by kpettinga** [comment]
@davekellam FYI, these positions are set manually:

https://github.com/ObjectiveSubject/cgu/blob/master/assets/css/sass/views/_page-ten-reasons.scss#L71-L144

**Comment by holliscooper-cgu** [comment]
We are getting (not good) feedback about this, so please make this update a priority. Thanks!

**Comment by Jessdwilson** [comment]
@kpettinga the client noted that the bubbles don't seem to be responsive the way they were previously, for instance in the attached shouldn't the entire graphic decrease in size rather than appear as consistent size bubbles in rows? 

<img width="942" alt="screen shot 2017-02-09 at 2 58 24 pm" src="https://cloud.githubusercontent.com/assets/1680051/22800713/3f5d4f46-eed8-11e6-97fd-042460eb07a8.png">

**Comment by kpettinga** [comment]
@Jessdwilson i've implemented scalability for the dots but at a certain point they need to fall into a grid in order to remain readable on small viewports. From 800px and up, the graphic will be scalable. Below that, they fall into a grid.

If you want total scalability at every viewport size, then this should just be an image.
