### ISSUE TITLE
Video playlists not playing

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#394]
Videos that are getting pulled in by the playlist shortcode don't play:

https://www.cgu.edu/alumni/benefits/professional-development-webinars/
https://www.cgu.edu/school/drucker-school-of-management/videos/

I'm using this shortcode on those pages: [cgu_video_playlist title="" user="" playlist=""]

I've tested in both Chrome and Firefox, with the same results.

The regular video shortcode works fine.

**Comment by davekellam** [comment]
An update here... I've been working on a fix for this problem, but have yet to find a solution.

Your usage of the shortcode is correct, and it is partially working (you wouldn't see the screenshots otherwise). The shortcode pulls in the playlist via API and generates the view on the fly. Right now there's an issue where the click event that generates the subsequent iframe embed isn't getting populated properly and fails.

**Comment by holliscooper-cgu** [comment]
Thanks, Dave. I swear this was working awhile ago. It was working for sure on the old version of the Drucker site, if that is helpful at all.

https://github.com/ObjectiveSubject/drucker

**Comment by davekellam** [comment]
This should be fixed up now. We tracked it down to a bug that was accidentally introduced to the JavaScript.
