### ISSUE TITLE
Video: Shortcode broken

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#414]
We are having some issues with the single video shortcode:
- caption="false" does not suppress the video title
- title="video title name" does not display that title on the page - the YouTube title is pulled and shown no matter what.

I haven't tested the video group shortcode to see if it's working correctly.

**Comment by davekellam** [comment]
Been looking into this, not entirely sure why the caption is rendering when it's set to false. Haven't been able to track down an older instance where it worked. It's possible that YouTube has changed some aspect of the API response. 

The single video shortcode doesn't appear to have a title parameter, only the video group and video playlist shortcodes.

**Comment by kpettinga** [comment]
@holliscooper-cgu the single video shortcode didn't support a "title" attribute, as Dave pointed out. 

Also, the documentation for the "caption" attribute was misleading, as it was never intended to hide a video's title. My apologies there. 

I've tweaked the shortcode so that there is an attribute to set or hide the title.

Set a custom title:    
`[cgu_video id="..." title="my custom title"]`

Hide the video's title:    
`[cgu_video id="..." title="false"]`

Leave the title attribute off to display video with it's default YouTube title:    
`[cgu_video id="..."]`
