### ISSUE TITLE
Psychology Program page not loading

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#42]
@kpettinga when I try to select psychology from the area of study dropdown the page doesn't fully load with the selections, attached is a screenshot of what I'm seeing 

![programs filters](https://cloud.githubusercontent.com/assets/1680051/16158473/57492f56-348b-11e6-9ea1-9f4d13ab7f16.png)

**Comment by kpettinga** [comment]
@Jessdwilson 

The API was throwing an error because a concentration wasn't chosen for the all the psychology programs. If fixed it so the error won't mess up the page anymore. 

So far, however, only Positive Health Psychology has a concentration chosen. The rest of the psych programs are just going to be listed without a concentration until they're assigned one. 

They can be assigned using the "concentration" field:

![image](https://cloud.githubusercontent.com/assets/1746410/16184672/76a76912-36e8-11e6-8dc9-de49feafc27d.png)
