### ISSUE TITLE
Programs that span schools

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#54]
@davekellam @kpettinga 
From Hollis: Programs that span schools (like Arts Management, which is both Drucker and School of Arts & Humanities) are supposed to have their own template that is not school branded. However, it doesn't look like that's being triggered in any way - for example, Arts Management (tagged on the back end as Drucker and SAH) shows up with the Drucker header.

**Comment by davekellam** [comment]
I've reworked the `get_schools()` function to return false if there are multiple schools. So, in effect they'll be unbranded, like the screenshot below. A program wouldn't get school specific menu items, because it can't choose between the two.
 
<img width="1244" alt="screen shot 2016-07-26 at 4 05 20 pm" src="https://cloud.githubusercontent.com/assets/60804/17153774/298bef06-534c-11e6-9656-55a16297a189.png">

Going to leave this open for now, just in case there are unintended side-effects elsewhere on the site.

**Comment by Jessdwilson** [comment]
@kpettinga this is also on issue when choosing a program through the Admissions pages, for example on Cost & Aid filtering to Art Business and clicking on the program takes you to the Drucker school page instead of a non school branded page

**Comment by kpettinga** [comment]
@Jessdwilson 

Programs need to be tagged with two different schools in order to be considered "multi-school". Art Business was only tagged with Drucker.
