### ISSUE TITLE
Navigation: sub-navigation sticky

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#60]
the sub-navigation across the site should be sticky

**Comment by kpettinga** [comment]
@jalbertgagnier @Jessdwilson @elliotarthur 

In a mockup from the client (see image), their image seems to suggest that the main top navigation should be sticky _**in addition**_ to the sub-navigation. We've done this kind of thing on previous websites and I always feel it takes up too much real-estate. It will be especially problematic for the CGU site on pages with a school-specific header because logos add quite a bit to the height.

So I'd like to advocate for either:
**a)** ONLY having the sub-navigation sticky, or
**b)** Having them both be sticky but the main navigation area is only seen while scrolling up.

![image](https://cloud.githubusercontent.com/assets/1746410/17655449/aa333cfe-62d8-11e6-8d3b-fbd354a2480b.png)

**Comment by jalbertgagnier** [comment]
I’d like that we suggest 
c) Have only Subnav when scrolling down, but topnav whenever you scroll up. I think that’s the best of both worlds.

**Comment by kpettinga** [comment]
@jalbertgagnier that's what I was suggesting with **b)** 😄 . Sounds like we're on the same page.

**Comment by elliotarthur** [comment]
@kpettinga I'd like to see the Subnav bolt onto the topnav when scrolling up! This way both are still visible, without compromising or hiding elements. Having to keep scrolling up and down to hide and reveal navigations seems cumbersome.

**Comment by kpettinga** [comment]
@elliotarthur I agree. I'm not completely happy with it. Getting these two items to work together and also have a pleasant animation transition has proved quite technically challenging.

To be honest, I think it's quite cumbersome for the header to be fixed at all, especially when it's a school header and the height is rather large (see image below). anchoring the subnav to the bottom then makes it taller still.

![screen shot 2016-08-18 at 11 10 58 am](https://cloud.githubusercontent.com/assets/1746410/17762050/d924854e-6536-11e6-88f0-cc81298fbfc4.png)

---
How would you feel about instead providing some kind of "back to top" link?

![nav options-02](https://cloud.githubusercontent.com/assets/1746410/17762058/e395c150-6536-11e6-9b8b-ced6e3452349.png)
OR
![nav options-01](https://cloud.githubusercontent.com/assets/1746410/17762068/0f3c5e5e-6537-11e6-8333-ea20f38ceba4.png)

**Comment by elliotarthur** [comment]
@kpettinga I think having the header fixed on scroll up is ok, as most people are done with reading the content and want to head back to the navigation to find another section of the site.

I totally agree it's going to take a lot of the space on a laptop screen. 

Also, I'm not a big fan of 'back to top' buttons. Mouses are there for that ;D

**Comment by kpettinga** [comment]
Currently the sub-nav is the sticky navigation element. Unless the client is unhappy with the current implementation im going to close this.
