### ISSUE TITLE
Faculty: include website or CV

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#69]
Hollis requested that we include the ability to link to a faculty website or CV which I think would make sense to include in the sidebar with Email, Degrees, etc. 

I see that they can create a custom field, but when I tried adding a Faculty Website custom field nothing changed on the site

**Comment by davekellam** [comment]
@Jessdwilson not sure what you mean by the create a custom field bit. There doesn't appear to be a spot to add website or cv to a People post type.

We would probably need to add two fields, one for website and one for a CV upload (assuming it would be a pdf uploaded, rather than a link to something?)

**Comment by Jessdwilson** [comment]
@davekellam yes, we should have two fields one for a website and one for a CV which will be a PDF they can upload. We should have this info appear in the sidebar of a Faculty landing page (attached)
![screen shot 2016-09-15 at 11 19 56 am](https://cloud.githubusercontent.com/assets/1680051/18555681/b2407bde-7b36-11e6-8259-ab13b34bbb19.png)

**Comment by kpettinga** [comment]
There are now fields in the backend to provide a website and CV (PDF)
