### ISSUE TITLE
Events: calendar search feature

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#93]
@kpettinga for the calendar search it appears you can only search for events within the selected day, week or month but you should be able to search for events that span all times

**Comment by kpettinga** [comment]
@Jessdwilson It doesn't seem like we're able to modify the search bar functionality to look at ALL events across time, not just in the current view.

If a user wants to search all events from any time, they need to use the regular search bar in the header. On search result pages we have labels for post types so the word "event" will appear above an event listing. I will also go ahead and add the day and time info to event posts in search results.

Perhaps we want to edit the language a bit on the events page so that users know the search bar is ONLY going to filter the events they already see, and not perform a site-wide search.

**Comment by kpettinga** [comment]
@Jessdwilson I've re-worded the filter inputs to try and indicate that searching only narrows your results: 
![image](https://cloud.githubusercontent.com/assets/1746410/19064300/ada635fa-8a36-11e6-9de1-775b1ae84f03.png)

Also, I've styled the events that appear in a regular search result page to look like the events listed in the calendar, so it's more obvious to the user they're looking at an event: 
![image](https://cloud.githubusercontent.com/assets/1746410/19064324/d4f0297c-8a36-11e6-97b3-a4d774431865.png)
